# Generated by Django 5.2 on 2025-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_predictions_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notified_before_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
