# Generated by Django 5.2 on 2025-04-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_notified_before_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryAlert',
        ),
    ]
