# Generated by Django 5.2 on 2025-04-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_inventoryalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='excel_file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.DeleteModel(
            name='DemandPrediction',
        ),
    ]
